### ISSUE TITLE
Get Amazon S3 URL of a video after upload is done

### ISSUE THREAD

**Issue by yasintanriverdi** [Ziggeo/Android-Client-SDK#25]
Is there a way to get the Amazon S3 URL of the video after upload operation is done?

**Comment by ibnutri** [comment]
Hi,

The S3 push service is not on the Client-SDK. Because it's done from the server. You can use webhook https://ziggeo.com/docs/api/webhooks to catch when the video is pushed to S3. The webhook names are `video_stream_push_success` and `video_stream_push_failed`. 

Full list of webhooks available is here https://ziggeo.com/docs/api/webhooks/list

**Comment by yasintanriverdi** [comment]
Thanks 👍
