### ISSUE TITLE
setSendImmediatly(false)  don't work.

### ISSUE THREAD

**Issue by wandersage** [Ziggeo/Android-Client-SDK#5]
Hi. I'm create new Ziggeo instance in Button onClickListener in Fragment like this 
Ziggeo ziggeo = new Ziggeo(getString(R.string.ziggeo_appid));
                ziggeo.setSendImmediately(false);
                ziggeo.createVideo(getActivity(), ziggeo_video_duration);
and use EventBus for OnVideoSent event. But video always sent after recording. What's wrong?
And next question. How can I sent video not immediately after recording?

**Comment by 3akat** [comment]
@wandersage 
Hi Anton,
Everything seems working fine.
When you set 
```java 
ziggeo.setSendImmediately(false);
```
Video will not be sent right after you've recorded it and you will have ability to play the video first.
Then when you press ok button the video will be sent.
![screenshot_1](https://cloud.githubusercontent.com/assets/2178533/12606123/e4d29e5e-c4db-11e5-9f9a-9ef957bec2f8.png)

Please, tell me if you still have any questions,
Thanks

**Comment by jiahaoliuliu** [comment]
Hi:
I am trying to work with the method attachRecorder setting the value setSendImmediately(false) but it does not seems to work. Checking the source code, the boolean ARG_SEND_IMMEDIATELY is passed to the class VideoRecorderFragment but never taked into account: The super class BaseRecorderFragment does use it to set the boolean mSendImmediately but this boolean is never used.

The reason why I am using this is fragment recorder instead of the fullscreen recorder is because the fullscreen recorder crashes when it tries to upload the video. Thus, I don't have any other option.

Please, could you fix it?

**Comment by 3akat** [comment]
Hi @jiahaoliuliu,
1. I couldn't reproduce your crash but tried to fix. Please check.
2. Why do you think ```setSendImmediately``` is not working? I've rechecked, everything working as expected. ```mSendImmediately``` is used in ```VideoRecorderFragment```. This argument just allow you to select cover shot before send a video. After cover shot selection the video will be sent.
Can you please describe how do you expect it should work?
